### ISSUE TITLE
When prefix is left blank, for preload task, task won't run

### ISSUE THREAD

**Issue by hagen** [SAP/grunt-openui5#16] opened 2015-09-29 03:56 UTC
Hi there,

I have similar grunt config to your sample-app, but use different directory names:

```
grunt.initConfig({

    dir: {
        src: 'src',
        dist: 'dist'
    },

    openui5_preload: {
        component: {
            options: {
                resources: {
                    cwd: '<%= dir.src %>',
                    prefix: ''
                },
                dest: '<%= dir.dist %>'
            },
            components: true
        }
    },
```

When run, I get:
Warning: No files found for pattern(s): "/**"! Use --force to continue.

I don't need/want a prefix. I've also noticed that if I start adding in prefixes to keep the warning quiet, the app doesn't use the Component-preload.js, it still reads in each of the Controllers/Views.

Snippet of my index.html:
    
    <script
        type="text/javascript"
        id="sap-ui-bootstrap"
        src="sdk/openui5-runtime-1.30.8/resources/sap-ui-core.js"
        data-sap-ui-theme="sap_bluecrystal"
        data-sap-ui-xx-bindingSyntax="complex"
        data-sap-ui-libs="sap.m"
        data-sap-ui-resourceroots='{
                "com.ffa.dash": "./",
                "view" : "./view",
                "util" : "./util",
                "thirdparty" : "./thirdparty"
        }'>
    </script>

Directory structure:
app
-- util
-- view
---- App.controller.js
---- App.view.xml

Declaration from App controller:

```
jQuery.sap.declare("view.App");

// Provides controller view.App
sap.ui.define(['jquery.sap.global', 'com/ffa/dash/util/Controller'],
function(jQuery, Controller) {
"use strict";

var App = Controller.extend("view.App", /** @lends view.App.prototype */ {

});

    return App;

}, /* bExport= */ true);
```

**Comment by matz3** [comment] 2015-09-29 10:51
Could you please provide the complete folder structure (including Component.js).
It might be a problem that you have multiple resourceroots which do not match with the Component's namespace.

**Comment by hagen** [comment] 2015-09-29 22:12
Certainly

![image](https://cloud.githubusercontent.com/assets/5161952/10179688/f75d5da0-674a-11e5-9e93-a4163eae1b7f.png)

**Comment by matz3** [comment] 2015-09-30 06:58
Okay, so the issue is that all your modules (views, controller, ...) have to be in the same namespace as the Component is. This is the reason why it did not use the preload.
So the easiest solution would be to remove the `view`, `util` and `thirdparty` resourceroot and adopt the module names to `com.ffa.dash.view.*`, `com.ffa.dash.util.*` and `com.ffa.dash.thirdparty.*`

Furthermore you need to configure the `prefix` with `com/ffa/dash` as this seems to be the namespace of your Component, which is not reflected by the folder structure.

**Comment by hagen** [comment] 2015-09-30 13:33
Thank you for the advice @matz3. I have done as you suggested, and the preload builds nicely. The application also runs in the browser. I have one further question however: the resources loaded by the preload file are located in a folder 'undefined', in the web inspector (Chrome). Is this to be expected, or is something still not quite right? See below...

![image](https://cloud.githubusercontent.com/assets/5161952/10194365/9aabc958-67cb-11e5-88ab-cb3eed3b43a3.png)

**Comment by matz3** [comment] 2015-10-01 13:59
This looks like an issue. I will look into it, thanks for reporting!

**Comment by hagen** [comment] 2017-02-09 20:50
Hi @matz3 we're you able to look into the undefined/ namespace prefix at all? It doesn't affect operation of Component-preload files, but is odd. I will look into this next week also.

**Comment by matz3** [comment] 2017-02-13 13:02
@hagen no, I did not have a deeper look into it. Please feel free to do so.

**Comment by matz3** [comment] 2019-09-30 09:20
I'm closing this issue as there wasn't an update since quite a while. Please let me know in case this is still relevant. Please also checkout the UI5 Tooling, which is the successor of the grunt tasks: https://sap.github.io/ui5-tooling/

**Closed by matz3** 2019-09-30 09:20 UTC
